version: "3.7"

services:
  php:
    build:
      context: ./environment/docker/php
      dockerfile: Dockerfile
      args:
        COMPOSER_VERSION: ${COMPOSER_VERSION}
    container_name: brewmap-php
    working_dir: /application
    volumes:
      - .:/application
    restart: always

  web:
    container_name: brewmap-web
    image: nginx:alpine
    working_dir: /application
    volumes:
      - .:/application
      - ./environment/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "13000:80"
    depends_on:
      - php
    restart: always
